version: "3.7"

services:
  frontend:
    build: ./frontend
    restart: always
    ports:
      - published: 2000
        target: 9000
    command: ["gatsby", "serve", "-H", "0.0.0.0"]

  rss:
    build: ./RSS_feed
    restart: always
    ports:
      - published: 2001
        target: 3000
    command: ["node", "index.js"]
